# raycast.gd was generated by Gemini LLM
extends RayCast3D

@export_category("Interaction Settings")
@export var interact_action : String = "interact"

# Changed type to Node to prevent hidden 'null' casting bugs
var interaction_ui: Node = null 
var current_interactable: InteractableComponent = null

func _ready() -> void:
	# Find the node in the scene tree that belongs to our group
	var ui_nodes = get_tree().get_nodes_in_group("interaction_ui")
	if ui_nodes.size() > 0:
		interaction_ui = ui_nodes[0]
		print("[LINK SUCCESS] Raycast found and connected to: ", interaction_ui.name)
	else:
		print("[LINK ERROR] Raycast could not find any node in the 'interaction_ui' group!")

func _physics_process(_delta: float) -> void:
	_scan_for_interactable()
	
func _scan_for_interactable() -> void:
	if is_colliding():
		var target = get_collider()
		if target:
			# OPTIONAL: Uncomment the line below to see everything your face hits in the console
			print("Looking at: ", target.name)
			
			for child in target.get_children():
				if child is InteractableComponent:
					current_interactable = child
					
					if interaction_ui and interaction_ui.has_method("show_prompt"):
						interaction_ui.show_prompt()
					return
	
	current_interactable = null
	if interaction_ui and interaction_ui.has_method("hide_prompt"):
		interaction_ui.hide_prompt()
		
func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed(interact_action):
		if current_interactable:
			print("[INTERACT] Successfully triggered interaction on: ", current_interactable.get_parent().name)
			current_interactable.interact()
